[env:m5stack-cardputer]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
build_type = release

; Cardputer-Adv official baseline: ESP32-S3FN8, 8MB flash, USB CDC on boot.
; Source tree is intentionally split by subsystem.
build_flags =
    -D ESP32S3
    -D CORE_DEBUG_LEVEL=0
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -Iinclude/core
    -Iinclude/shell
    -Iinclude/lab
    -Iinclude/hw

lib_deps =
    M5Cardputer=https://github.com/m5stack/M5Cardputer
    h2zero/NimBLE-Arduino
